import os

AZURE_OPENAI_API_KEY = '6WQnEWscNtH4X4ie1VJX9NHo5BLbRjFp6W3SLpSrBtiatQFX1gudJQQJ99BCACYeBjFXJ3w3AAABACOGWKkR'
AZURE_OPENAI_ENDPOINT = 'https://yipeng-openai.openai.azure.com/'

# AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
# AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")