learning:
  algorithm:
    class_name: TDO
    clip_param: 0.2
    desired_kl: 0.01
    entropy_coef: 0.01
    gamma: 0.99
    lam: 0.95
    learning_rate: 0.001
    max_grad_norm: 1.0
    num_learning_epochs: 5
    num_mini_batches: 4
    schedule: adaptive
    use_clipped_value_loss: true
    value_loss_coef: 1.0
    td_entropy_coef: 0.0
    return_boosting_coef: 0.0
    action_noise_threshold: 0.0
  policy:
    activation: elu
    actor_hidden_dims:
    - 512
    - 256
    - 128
    class_name: ActorCriticTDO
    critic_hidden_dims:
    - 512
    - 256
    - 128
    init_noise_std: 1.0
  temporal_distribution:
    learning_rate: 0.001
    class_name: TemporalDistribution
  PPO: false
  empirical_normalization: false
  exp_name: null
  num_steps_per_env: 24
  reset_rate: 0.0
  print_infos: true
  record_interval: 50
  save_interval: 100
  seed: 1
  wandb_entity: ziyanx02
  wandb_project: Gait
environment:
  PPO: false
  urdf_path: urdf/T12/urdf/T12_simplified.urdf
  robot_scale: 1.0
  links_to_keep:
  - Foot1
  - Foot2
  - Foot3
  - Foot4
  - Foot5
  - Foot6
  num_actions: 36
  num_dofs: 36
  num_states: 82
  termination_contact_link_names:
  - Body
  - Hip1
  - Hip2
  - Hip3
  - Hip4
  - Hip5
  - Hip6
  - Thigh1
  - Thigh2
  - Thigh3
  - Thigh4
  - Thigh5
  - Thigh6
  - Knee1
  - Knee2
  - Knee3
  - Knee4
  - Knee5
  - Knee6
  - Shin1
  - Shin2
  - Shin3
  - Shin4
  - Shin5
  - Shin6
  - Ankle1
  - Ankle2
  - Ankle3
  - Ankle4
  - Ankle5
  - Ankle6
  penalized_contact_link_names:
  - Body
  - Hip1
  - Hip2
  - Hip3
  - Hip4
  - Hip5
  - Hip6
  - Thigh1
  - Thigh2
  - Thigh3
  - Thigh4
  - Thigh5
  - Thigh6
  - Knee1
  - Knee2
  - Knee3
  - Knee4
  - Knee5
  - Knee6
  - Shin1
  - Shin2
  - Shin3
  - Shin4
  - Shin5
  - Shin6
  - Ankle1
  - Ankle2
  - Ankle3
  - Ankle4
  - Ankle5
  - Ankle6
  feet_link_names:
  - Foot1
  - Foot2
  - Foot3
  - Foot4
  - Foot5
  - Foot6
  base_link_name:
  - Body
  PD_stiffness:
    ? ''
    : 40000.0
  PD_damping:
    ? ''
    : 7000.0
  armature: 0.05
  dof_damping: 0.0
  action_scale: 0.25
  clip_actions: 100.0
  control_freq: 50
  decimation: 4
  delay_action: true
  dof_names:
  - HY1
  - HY2
  - HY3
  - HY4
  - HY5
  - HY6
  - HP1
  - HP2
  - HP3
  - HP4
  - HP5
  - HP6
  - KP1
  - KP2
  - KP3
  - KP4
  - KP5
  - KP6
  - KR1
  - KR2
  - KR3
  - KR4
  - KR5
  - KR6
  - AP1
  - AP2
  - AP3
  - AP4
  - AP5
  - AP6
  - AR1
  - AR2
  - AR3
  - AR4
  - AR5
  - AR6
  episode_length_s: 20.0
  period_length_s: 0.5
  use_timeout: true
  reset_after_termination: true
  termination_if_height_lower_than: 0.0
  termination_if_pitch_greater_than: 0.4
  termination_if_roll_greater_than: 0.4
  base_init_pos:
  - 0.0
  - 0.0
  - 1.9
  base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  body_init_pos:
  - 0.0
  - 0.0
  - 1.9
  body_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  default_joint_angles:
    HY1: 0.0
    HY2: 0.0
    HY3: 0.0
    HY4: 0.0
    HY5: 0.0
    HY6: 0.0
    HP1: 0.0
    HP2: 0.0
    HP3: 0.0
    HP4: 0.0
    HP5: 0.0
    HP6: 0.0
    KP1: 1.5
    KP2: 1.5
    KP3: 1.5
    KP4: 1.5
    KP5: 1.5
    KP6: 1.5
    KR1: 0.0
    KR2: 0.0
    KR3: 0.0
    KR4: 0.0
    KR5: 0.0
    KR6: 0.0
    AP1: 0.0
    AP2: 0.0
    AP3: 0.0
    AP4: 0.0
    AP5: 0.0
    AP6: 0.0
    AR1: 0.0
    AR2: 0.0
    AR3: 0.0
    AR4: 0.0
    AR5: 0.0
    AR6: 0.0
  resampling_time_s: 4.0
  randomize_base_mass: true
  added_mass_range:
  - -1.0
  - 3.0
  randomize_com_displacement: true
  com_displacement_range:
  - -0.01
  - 0.01
  randomize_friction: true
  friction_range:
  - 0.2
  - 1.5
  randomize_kd_scale: true
  kd_scale_range:
  - 0.8
  - 1.2
  randomize_kp_scale: true
  kp_scale_range:
  - 0.8
  - 1.2
  randomize_motor_offset: true
  motor_offset_range:
  - -0.02
  - 0.02
  randomize_motor_strength: false
  motor_strength_range:
  - 0.9
  - 1.1
  pos_randomization: 0.0
  rot_randomization: 0.1
  dof_pos_randomization: 0.3
  max_push_vel_xy: 1.0
  push_interval_s: -1
  use_terrain: false
  command:
    lin_vel_x_range:
    - 0.0
    - 5.0
    lin_vel_y_range:
    - 0.0
    - 0.0
    ang_vel_range:
    - 0.0
    - 0.0
  gait:
    base_height_target: 1.71
    frequency:
    - 0.8
    - 0.8
    - 0.8
    - 0.8
    - 0.8
    - 0.8
    duration:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    offset:
    - 0.0
    - 0.5
    - 0.0
    - 0.5
    - 0.0
    - 0.5
    feet_height_target:
    - 0.684
    - 0.684
    - 0.684
    - 0.684
    - 0.684
    - 0.684
    stationary_position:
    - - 2.84698
      - 1.64
    - - 0.00377
      - 3.29
    - - -2.84318
      - 1.65
    - - -2.84699
      - -1.64
    - - -0.00378
      - -3.29
    - - 2.84318
      - -1.65
  observation:
    num_obs: 123
    num_priv_obs: 162
    obs_noise:
      ang_vel: 0.1
      dof_pos: 0.01
      dof_vel: 0.5
      gravity: 0.02
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      lin_vel: 1.0
  reward:
    reward_scales:
      lin_vel: 1.0
      ang_vel: 0.5
      alive: 10.0
      ang_vel_xy: -0.05
      base_height: -30.0
      dof_acc: -0.05
      dof_vel: -0.01
      dof_pos_diff: -0.1
      lin_vel_z: -2.0
      orientation: -5.0
      contact_force: -5.0
      contact_vel: -5.0
      feet_height: -400.0
      feet_pos: -30.0
      action_smoothness_1: -0.1
      action_smoothness_2: -0.1
      torques: -0.0001
    soft_dof_pos_limit: 0.9
    tracking_sigma: 0.25
reward_tuning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
