learning:
  algorithm:
    class_name: TDO
    clip_param: 0.2
    desired_kl: 0.01
    entropy_coef: 0.01
    gamma: 0.99
    lam: 0.95
    learning_rate: 0.001
    max_grad_norm: 1.0
    num_learning_epochs: 5
    num_mini_batches: 4
    schedule: adaptive
    use_clipped_value_loss: true
    value_loss_coef: 1.0
    td_entropy_coef: 0.0
    return_boosting_coef: 0.0
    action_noise_threshold: 0.0
  policy:
    activation: elu
    actor_hidden_dims:
    - 512
    - 256
    - 128
    class_name: ActorCriticTDO
    critic_hidden_dims:
    - 512
    - 256
    - 128
    init_noise_std: 1.0
  temporal_distribution:
    learning_rate: 0.001
    class_name: TemporalDistribution
  PPO: false
  empirical_normalization: false
  exp_name: null
  num_steps_per_env: 24
  reset_rate: 0.0
  print_infos: true
  record_interval: 50
  save_interval: 100
  seed: 1
  wandb_entity: ziyanx02
  wandb_project: TDO
environment:
  PPO: false
  # asset
  urdf_path: urdf/g1/g1_12dof.urdf
  links_to_keep:
  - left_ankle_roll_link
  - left_ankle_roll_link
  num_actions: 12
  num_dofs: 12
  num_states: 34
  termination_contact_link_names:
  - pelvis
  penalized_contact_link_names:
  - pelvis
  feet_link_names:
  - left_ankle_roll_link
  - left_ankle_roll_link
  base_link_name:
  - pelvis
  # control
  PD_stiffness:
    left_hip_pitch_joint: 100.
    left_hip_roll_joint: 100.
    left_hip_yaw_joint: 100.
    left_knee_joint: 200.
    left_ankle_pitch_joint: 20.
    left_ankle_roll_joint: 20.
    right_hip_pitch_joint: 100.
    right_hip_roll_joint: 100.
    right_hip_yaw_joint: 100.
    right_knee_joint: 200.
    right_ankle_pitch_joint: 20.
    right_ankle_roll_joint: 20.
  PD_damping:
    left_hip_pitch_joint: 5.0
    left_hip_roll_joint: 5.0
    left_hip_yaw_joint: 5.0
    left_knee_joint: 5.0
    left_ankle_pitch_joint: 0.2
    left_ankle_roll_joint: 0.1
    right_hip_pitch_joint: 5.0
    right_hip_roll_joint: 5.0
    right_hip_yaw_joint: 5.0
    right_knee_joint: 5.0
    right_ankle_pitch_joint: 0.2
    right_ankle_roll_joint: 0.1
  armature: 0.05
  dof_damping: 0.0
  action_scale: 0.25
  clip_actions: 100.0
  control_freq: 50
  decimation: 4
  delay_action: true
  dof_names:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  # termination
  episode_length_s: 20.0
  period_length_s: 0.5
  use_timeout: true
  reset_after_termination: true
  termination_if_height_lower_than: 0.0
  termination_if_pitch_greater_than: 0.3
  termination_if_roll_greater_than: 0.3
  # init pos
  base_init_pos:
  - 0.0
  - 0.0
  - 0.85
  base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  default_joint_angles:
    left_hip_yaw_joint: 0.
    left_hip_roll_joint: 0.
    left_hip_pitch_joint: -0.1
    left_knee_joint: 0.3
    left_ankle_pitch_joint: -0.2
    left_ankle_roll_joint: 0.
    right_hip_yaw_joint: 0.
    right_hip_roll_joint: 0.
    right_hip_pitch_joint: -0.1
    right_knee_joint: 0.3
    right_ankle_pitch_joint: -0.2
    right_ankle_roll_joint: 0.
  # domain randomization
  resampling_time_s: 4.0
  randomize_base_mass: true
  added_mass_range:
  - -1.0
  - 3.0
  randomize_com_displacement: true
  com_displacement_range:
  - -0.01
  - 0.01
  randomize_friction: true
  friction_range:
  - 0.2
  - 1.5
  randomize_kd_scale: true
  kd_scale_range:
  - 0.8
  - 1.2
  randomize_kp_scale: true
  kp_scale_range:
  - 0.8
  - 1.2
  randomize_motor_offset: true
  motor_offset_range:
  - -0.02
  - 0.02
  randomize_motor_strength: false
  motor_strength_range:
  - 0.9
  - 1.1
  # random initialization
  pos_randomization: 0.0
  rot_randomization: 0.1
  dof_pos_randomization: 0.3
  # random push
  max_push_vel_xy: 1.0
  push_interval_s: -1
  use_terrain: false
  command:
    lin_vel_x_range:
    - -1.0
    - 1.0
    lin_vel_y_range:
    - -1.0
    - 1.0
    ang_vel_range:
    - -2.0
    - 2.0
  observation:
    num_obs: 45
    num_priv_obs: 60
    obs_noise:
      ang_vel: 0.1
      dof_pos: 0.01
      dof_vel: 0.5
      gravity: 0.02
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      lin_vel: 1.0
  reward:
    base_height_target: 0.73
    reward_scales:
      lin_vel: 1.0
      ang_vel: 0.5
      action_rate: -0.01
      ang_vel_xy: -0.05
      base_height: -5.0
      collision: -1.0
      dof_acc: -2.5e-07
      dof_pos_diff: -0.3
      dof_vel: -0.0
      feet_air_time: 1.0
      lin_vel_z: -2.0
      orientation: -1.0
      torques: -0.0001
      terminate: -30.0
    soft_dof_pos_limit: 0.9
    tracking_sigma: 0.25