learning:
  algorithm:
    class_name: TDO
    clip_param: 0.2
    desired_kl: 0.01
    entropy_coef: 0.01
    gamma: 0.99
    lam: 0.95
    learning_rate: 0.001
    max_grad_norm: 1.0
    num_learning_epochs: 5
    num_mini_batches: 4
    schedule: adaptive
    use_clipped_value_loss: true
    value_loss_coef: 1.0
    td_entropy_coef: 0.0
    return_boosting_coef: 0.0
    action_noise_threshold: 0.0
  policy:
    activation: elu
    actor_hidden_dims:
    - 512
    - 256
    - 128
    class_name: ActorCriticTDO
    critic_hidden_dims:
    - 512
    - 256
    - 128
    init_noise_std: 1.0
  temporal_distribution:
    learning_rate: 0.001
    class_name: TemporalDistribution
  PPO: false
  empirical_normalization: false
  exp_name: null
  num_steps_per_env: 24
  reset_rate: 0.0
  print_infos: true
  record_interval: 50
  save_interval: 100
  seed: 1
  wandb_entity: ziyanx02
  wandb_project: Gait
environment:
  PPO: false
  # asset
  urdf_path: urdf/go2/urdf/go2.urdf
  links_to_keep:
  - FL_foot
  - FR_foot
  num_actions: 12
  num_dofs: 12
  num_states: 34
  termination_contact_link_names:
  - base
  - thigh
  penalized_contact_link_names:
  - base
  - thigh
  - calf
  - RL_foot
  - RR_foot
  feet_link_names:
  - FL_foot
  - FR_foot
  base_link_name:
  - base
  # control
  PD_stiffness:
    joint: 30.0
  PD_damping:
    joint: 2.0
  armature: 0.05
  dof_damping: 0.0
  action_scale: 0.25
  clip_actions: 100.0
  control_freq: 50
  decimation: 4
  delay_action: true
  dof_names:
  - FR_hip_joint
  - FR_thigh_joint
  - FR_calf_joint
  - FL_hip_joint
  - FL_thigh_joint
  - FL_calf_joint
  - RR_hip_joint
  - RR_thigh_joint
  - RR_calf_joint
  - RL_hip_joint
  - RL_thigh_joint
  - RL_calf_joint
  # termination
  episode_length_s: 20.0
  period_length_s: 0.5
  use_timeout: true
  reset_after_termination: true
  termination_if_height_lower_than: 0.0
  termination_if_pitch_greater_than: 0.4
  termination_if_roll_greater_than: 0.4
  # init pos
  base_init_pos:
  - 0.0
  - 0.0
  - 0.5066820859909057
  base_init_quat:
  - -0.9238795638084412
  - 0.0
  - -0.3826833963394165
  - -2.659523374859418e-07
  default_joint_angles:
    FL_calf_joint: -1.3790717124938965
    FL_hip_joint: 0.0533900260925293
    FL_thigh_joint: 0.5249806642532349
    FR_calf_joint: -1.379075527191162
    FR_hip_joint: -0.05338793992996216
    FR_thigh_joint: 0.5249819159507751
    RL_calf_joint: -1.6129530668258667
    RL_hip_joint: 0.06433446705341339
    RL_thigh_joint: 0.6309767961502075
    RR_calf_joint: -1.6129592657089233
    RR_hip_joint: -0.06433191150426865
    RR_thigh_joint: 0.6309773325920105

  base_reset_pos:
  - 0.0
  - 0.0
  - 0.35
  base_reset_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  reset_joint_angles:
    FL_calf_joint: -1.5
    FL_hip_joint: 0.0
    FL_thigh_joint: 0.8
    FR_calf_joint: -1.5
    FR_hip_joint: 0.0
    FR_thigh_joint: 0.8
    RL_calf_joint: -1.5
    RL_hip_joint: 0.0
    RL_thigh_joint: 1.0
    RR_calf_joint: -1.5
    RR_hip_joint: 0.0
    RR_thigh_joint: 1.0

  # domain randomization
  resampling_time_s: 4.0
  randomize_base_mass: true
  added_mass_range:
  - -1.0
  - 3.0
  randomize_com_displacement: true
  com_displacement_range:
  - -0.01
  - 0.01
  randomize_friction: true
  friction_range:
  - 0.2
  - 1.5
  randomize_kd_scale: true
  kd_scale_range:
  - 0.8
  - 1.2
  randomize_kp_scale: true
  kp_scale_range:
  - 0.8
  - 1.2
  randomize_motor_offset: true
  motor_offset_range:
  - -0.02
  - 0.02
  randomize_motor_strength: false
  motor_strength_range:
  - 0.9
  - 1.1
  # random initialization
  pos_randomization: 0.0
  rot_randomization: 0.1
  dof_pos_randomization: 0.3
  # random push
  max_push_vel_xy: 1.0
  push_interval_s: -1
  use_terrain: false
  command:
    lin_vel_x_range:
    - -1.0
    - 1.0
    lin_vel_y_range:
    - -0.5
    - 0.5
    ang_vel_range:
    - -1.0
    - 1.0
  gait:
    base_height_target: 0.4001657962799072
    duration:
    - 0.5
    - 0.5
    frequency:
    - 3.0
    - 3.0
    offset:
    - 0.0
    - 0.5
    feet_height_target: 
    - 0.12
    - 0.12
    stationary_position:
    - - -0.05051339417695999
      - 0.15916676819324493
    - - -0.050512880086898804
      - -0.15916594862937927

  observation:
    num_obs: 47 # 45 + 2(num_feet)
    num_priv_obs: 62 # 60 + 2(num_feet)
    obs_noise:
      ang_vel: 0.1
      dof_pos: 0.01
      dof_vel: 0.5
      gravity: 0.02
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      lin_vel: 1.0
  reward:
    reward_scales:
      action_smoothness_1: -0.05
      action_smoothness_2: -0.05
      alive: 10.0
      ang_vel: 1.0
      ang_vel_xy: -0.05
      base_height: -10.0
      collision: -1.0
      contact_force: -10.0
      contact_vel: -5.0
      dof_acc: -0.05
      dof_pos_diff: -0.2
      dof_vel: -0.01
      feet_height: -200.0
      feet_pos: -20.0
      lin_vel: 2.0
      lin_vel_z: -2.0
      orientation: -5.0
      torques: -0.0001

    soft_dof_pos_limit: 0.9
    tracking_sigma: 0.25

reward_tuning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10