learning:
  algorithm:
    class_name: TDO
    clip_param: 0.2
    desired_kl: 0.01
    entropy_coef: 0.01
    gamma: 0.99
    lam: 0.95
    learning_rate: 0.001
    max_grad_norm: 1.0
    num_learning_epochs: 5
    num_mini_batches: 4
    schedule: adaptive
    use_clipped_value_loss: true
    value_loss_coef: 1.0
    td_entropy_coef: 0.0
    return_boosting_coef: 0.0
    action_noise_threshold: 0.0
  policy:
    activation: elu
    actor_hidden_dims:
    - 512
    - 256
    - 128
    class_name: ActorCriticTDO
    critic_hidden_dims:
    - 512
    - 256
    - 128
    init_noise_std: 1.0
  temporal_distribution:
    learning_rate: 0.001
    class_name: TemporalDistribution
  PPO: false
  empirical_normalization: false
  exp_name: null
  num_steps_per_env: 24
  reset_rate: 0.0
  print_infos: true
  record_interval: 50
  save_interval: 100
  seed: 1
  wandb_entity: ziyanx02
  wandb_project: Gait
environment:
  PPO: false
  # asset
  urdf_path: urdf/leap_hand/leap_hand_right_glb.urdf
  robot_scale: 3.0
  links_to_keep:
    - index_tip_head
    - middle_tip_head
    - ring_tip_head
    - thumb_tip_head
  num_actions: 16
  num_dofs: 16
  num_states: 42
  termination_contact_link_names:
  - base
  penalized_contact_link_names:
  - base
  - mcp_joint
  - pip
  - dip
  feet_link_names:
  - index_tip_head
  - middle_tip_head
  - ring_tip_head
  - thumb_tip_head
  base_link_name:
  - base
  # control
  PD_stiffness:
    '' : 20.0
  PD_damping:
    '' : 0.5
  armature: 0.05
  dof_damping: 0.0
  action_scale: 0.25
  clip_actions: 100.0
  control_freq: 50
  decimation: 4
  delay_action: true
  dof_names:
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  # termination
  episode_length_s: 20.0
  period_length_s: 0.5
  use_timeout: true
  reset_after_termination: true
  termination_if_height_lower_than: 0.0
  termination_if_pitch_greater_than: 0.4
  termination_if_roll_greater_than: 0.4
  # init pos
  base_init_pos:
  - 0.0
  - 0.0
  - 0.20
  base_init_quat:
  - 0.7071
  - 0.0
  - 0.7071
  - 0.0
  default_joint_angles:
    '1' : 0.393
    '5' : 0.393
    '9' : 0.449
    '12' : 0.524
    '0' : -0.524
    '4' : 0
    '8' : 0.524
    '13' : 2.2
    '2' : 0.449
    '6' : 0.393
    '10' : 0.449
    '14' : 0.524
    '3' : 0.449
    '7' : 0.393
    '11' : 0.449
    '15' : 0.524
  # domain randomization
  resampling_time_s: 4.0
  randomize_base_mass: true
  added_mass_range:
  - -1.0
  - 3.0
  randomize_com_displacement: true
  com_displacement_range:
  - -0.01
  - 0.01
  randomize_friction: true
  friction_range:
  - 0.2
  - 1.5
  randomize_kd_scale: true
  kd_scale_range:
  - 0.8
  - 1.2
  randomize_kp_scale: true
  kp_scale_range:
  - 0.8
  - 1.2
  randomize_motor_offset: true
  motor_offset_range:
  - -0.02
  - 0.02
  randomize_motor_strength: false
  motor_strength_range:
  - 0.9
  - 1.1
  # random initialization
  pos_randomization: 0.0
  rot_randomization: 0.1
  dof_pos_randomization: 0.3
  # random push
  max_push_vel_xy: 1.0
  push_interval_s: -1
  use_terrain: false
  command:
    lin_vel_x_range:
    - 0.0
    - 0.0
    lin_vel_y_range:
    - 0
    - 0
    ang_vel_range:
    - -0.3
    - 0.3
  gait:
    # the order of feet is defined by feet_link_name
    base_height_target: 0.12
    frequency: [3.0, 3.0, 3.0, 3.0]
    duration: [0.5, 0.5, 0.5, 0.5]
    offset: [0.5, 0, 0.5, 0] 
    feet_height_target: [0.05, 0.05, 0.05, 0.05]
    stationary_position:
      - [0.14, 0.09]
      - [0.17, 0.00] 
      - [0.14, -0.09]
      - [-0.05, 0.09]

  observation:
    num_obs: 61 # 45 + 2(num_feet)
    num_priv_obs: 80 # 60 + 2(num_feet)
    obs_noise:
      ang_vel: 0.1
      dof_pos: 0.01
      dof_vel: 0.5
      gravity: 0.02
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      lin_vel: 1.0
  reward:
    reward_scales:
      lin_vel: 1.0
      ang_vel: 0.5
      action_rate: -0.01
      ang_vel_xy: -0.05
      base_height: -5.0
      collision: -1.0
      dof_acc: -2.5e-07
      dof_vel: -0.0
      dof_pos_diff: -0.1
      feet_air_time: 1.0
      lin_vel_z: -2.0
      orientation: -5.0
      alive: 10.0
      
      # Additional in Gait
      contact_force: -5.
      contact_vel: -5.
      feet_height: -100.
      feet_pos: -7.0
      # Additional auxiliary
      action_smoothness_1: -0.01
      action_smoothness_2: -0.01
      feet_slip: -0.04
    

    soft_dof_pos_limit: 0.9
    tracking_sigma: 0.25